namespace: community
name: bacnet
version: 1.0.0
description: BACnet operations collection using bacpypes
license: MIT
authors:
  - Sagar Paul (KB-perByte)
dependencies: {}
repository: https://github.com/KB-perByte/community.bacnet
documentation: https://github.com/KB-perByte/community.bacnet/README.md
issues: https://github.com/KB-perByte/community.bacnet/issues
keywords:
  - bacnet
  - building automation
  - iot
